# Generated by Django 5.0.3 on 2024-04-09 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagen',
            old_name='info',
            new_name='pregunta',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='question',
        ),
    ]
