# Generated by Django 5.0.3 on 2024-04-23 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_usuario_imagen_opcion_pregunta_codigo_delete_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='date',
        ),
    ]
