# Generated by Django 5.0.3 on 2024-05-07 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_imagen_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='opcion',
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usuario'),
        ),
    ]
