# Generated by Django 5.0.3 on 2024-05-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_pregunta_imagen_imagen_pregunta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='codigo',
        ),
    ]
