# Generated by Django 5.0.3 on 2024-05-16 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_pregunta_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='pregunta',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='imagen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.imagen'),
        ),
    ]
