# Generated by Django 5.0.3 on 2024-05-16 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_imagen_pregunta_pregunta_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuarioo',
        ),
    ]
