# Generated by Django 5.0.3 on 2024-05-16 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_usuario_usuarioo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarioo',
            new_name='Codigo',
        ),
    ]
