# Generated by Django 5.0.3 on 2024-05-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_usuarioo_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='pregunta',
            new_name='respuesta',
        ),
    ]
