# Generated by Django 5.0.3 on 2025-03-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_pregunta_pregunta_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='usuario_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
